Fix Worker TypeScript check failures
After commit 2384f08 things were failing with:
```
$ node_modules/.bin/tsc --noEmit --project worker/tsconfig.json
worker/disk.ts:24:26 - error TS2339: Property 'default' does not exist on type 'CacheStorage'.
24     const cache = caches.default;
```

This was a side effect of the worker/tsconfig.json changes to accomodate
run-def.ts being pulled in (and thus more client code). Specifically, the
browser `CacheStorage` definition was shadowing the Cloudflare worker one.

Undo the tsconfig.json changes, and instead add a stub declaration for
the client code that we expect to run in the worker, so that we can
avoid type checking the real implementation (and thus pullin in their
types). This is preferable to refactoring run-def.ts to avoid the extra
dependencies (and in any case, the client code is checked in the main
project).